spring.application.name=portifolio-api
server.port=8080

# Conexão com o MySQL via Container Docker
spring.datasource.url=jdbc:mysql://devportfolio-db:3306/portfolio_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=rootpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
# Mude para never para impedir que o script data.sql quebre a inicialização antes das tabelas existirem:
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true