name: Pipeline Backend CI/CD

on:
  push:
    branches: [ "main", "Pipeline" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar JDK Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Dar permissão de execução ao Maven Wrapper (se houver)
        run: chmod +x portfolio-api/mvnw || true

      - name: Executar Testes Unitários e Build Automatizado
        run: mvn clean package -f portfolio-api/pom.xml

      - name: Análise Estática / Lint Simulado
        run: echo "Análise de Qualidade concluída com sucesso!"